name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          plugin_introduction: yes
          
          plugin_languages: yes
          plugin_languages_recent_days: 0
          plugin_languages_threshold: 1%
          plugin_languages_sections: most-used
          
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          
          plugin_code: yes
          plugin_code_lines: 20
          
          plugin_repositories: yes
          plugin_repositories_pinned: 6
